"use client";

import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { STRATEGY, SETUP_STAGES, fmt } from "@/lib/strategy";

type View = "Home" | "Market" | "POI" | "Setups" | "Journal" | "Performance" | "Backtest" | "Strategy" | "Calendar" | "AI Copilot" | "Psychology" | "Settings";
type Tone = "neutral" | "green" | "amber" | "coral" | "blue";
type Fib = { direction: "BULLISH" | "BEARISH"; swingLow: number; swingHigh: number; stop: number; poi: number; tp1: number; tp2: number } | null;
type TF = { timeframe: string; trend: string; structure: string; confidence: number };
type MarketState = { live: boolean; price: number | null; changePct: number | null; updatedAt: string | null; marketOpen: boolean; marketStatus?: string; message?: string };
type AnalysisState = { live: boolean; current: number | null; status: string; direction: "BULLISH" | "BEARISH" | null; reasons: string[]; fibonacci: Fib; liquidity: { swept: boolean; type: string }; timeframes: TF[]; updatedAt: string | null };

const primary: { id: View; icon: string }[] = [
  { id: "Home", icon: "⌂" }, { id: "Market", icon: "⌁" }, { id: "POI", icon: "◎" }, { id: "Setups", icon: "▣" }, { id: "Journal", icon: "□" },
];
const more: { id: View; icon: string; desc: string }[] = [
  { id: "Performance", icon: "↗", desc: "Edge, risk and execution" }, { id: "Backtest", icon: "↻", desc: "Test the rules" }, { id: "Strategy", icon: "✦", desc: "POI methodology" }, { id: "Calendar", icon: "□", desc: "Macro events" }, { id: "AI Copilot", icon: "✧", desc: "Explain verified context" }, { id: "Psychology", icon: "◌", desc: "Process and discipline" }, { id: "Settings", icon: "⚙", desc: "System preferences" },
];

const emptyMarket: MarketState = { live: false, price: null, changePct: null, updatedAt: null, marketOpen: false };
const emptyAnalysis: AnalysisState = { live: false, current: null, status: "UNKNOWN", direction: null, reasons: [], fibonacci: null, liquidity: { swept: false, type: "NONE" }, timeframes: [], updatedAt: null };

function useLiveMarket() {
  const [market, setMarket] = useState<MarketState>(emptyMarket);
  const [analysis, setAnalysis] = useState<AnalysisState>(emptyAnalysis);
  const refresh = async () => {
    try { const response = await fetch("/api/market", { cache: "no-store" }); const data = await response.json() as MarketState; setMarket(data); } catch { setMarket((current) => ({ ...current, live: false })); }
    try { const response = await fetch("/api/analysis", { cache: "no-store" }); const data = await response.json() as AnalysisState; setAnalysis(data); } catch { setAnalysis((current) => ({ ...current, live: false })); }
  };
  useEffect(() => { void refresh(); const id = window.setInterval(() => void refresh(), 5000); return () => window.clearInterval(id); }, []);
  return { market, analysis };
}

function Pill({ children, tone = "neutral" }: { children: React.ReactNode; tone?: Tone }) { return <span className={`ip-pill ${tone}`}>{children}</span>; }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`ip-card ${className}`}>{children}</section>; }
function Row({ label, value, note, tone = "" }: { label: string; value: string; note?: string; tone?: string }) { return <div className="ip-row"><div><span>{label}</span>{note && <small>{note}</small>}</div><strong className={tone}>{value}</strong></div>; }
function price(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? "—" : fmt(value); }
function tf(data: AnalysisState, name: string) { return data.timeframes.find((item) => item.timeframe === name); }
function statusLabel(status: string) { return status === "CONFIRMED" ? "CONFIRMED" : status === "WAIT" ? "WAITING" : status === "DEVELOPING" ? "DEVELOPING" : "UNKNOWN"; }

function Home({ go, market, analysis }: { go: (v: View) => void; market: MarketState; analysis: AnalysisState }) {
  const fib = analysis.fibonacci;
  const w = tf(analysis, "W1"), d = tf(analysis, "D1"), h1 = tf(analysis, "H1");
  return <div className="ip-page"><div className="ip-greeting"><div><span>TRADER OS</span><h1>Good session.</h1><p>Live XAU/USD context. No synthetic prices.</p></div><div className="ip-avatar">M</div></div>
    <Card className="ip-hero-card"><div className="ip-hero-top"><div><Pill tone={market.live ? "green" : "amber"}>{market.marketOpen ? "LIVE FEED" : "LAST PROVIDER QUOTE"}</Pill><span className="ip-live"><i/> XAU/USD</span></div><span className="ip-time">M15 EXECUTION</span></div><div className="ip-hero-price"><strong>{price(market.price)}</strong><span>USD</span></div><div className="ip-hero-state"><div><small>SETUP STATE</small><b>{statusLabel(analysis.status)}</b><p>{analysis.reasons[analysis.reasons.length - 1] || market.message || "Waiting for verified market data."}</p></div><button onClick={() => go("POI")}>Open POI <span>›</span></button></div></Card>
    <div className="ip-section-head"><h2>System status</h2><button onClick={() => go("Strategy")}>Rules ›</button></div><div className="ip-grid-2"><Card><small className="ip-label">WEEKLY / DAILY</small><div className={`ip-big ${w?.trend === "BEARISH" && d?.trend === "BEARISH" ? "coral" : ""}`}>{w?.trend === d?.trend ? w?.trend ?? "UNKNOWN" : "UNKNOWN"}</div><p>Higher-timeframe alignment</p></Card><Card><small className="ip-label">H1 STRUCTURE</small><div className={`ip-big ${h1?.structure === "BEARISH" || h1?.structure === "SHIFT" ? "green" : ""}`}>{h1?.structure ?? "UNKNOWN"}</div><p>Verified from provider candles</p></Card></div>
    <Card><div className="ip-card-head"><div><h3>Setup progression</h3><p>{analysis.status === "UNKNOWN" ? "Analysis unavailable" : `${analysis.status} · live evaluation`}</p></div><Pill tone="blue">0.71 POI</Pill></div><div className="ip-progress"><span style={{ width: `${analysis.status === "CONFIRMED" ? 100 : analysis.status === "WAIT" ? 75 : analysis.status === "DEVELOPING" ? 50 : 10}%` }}/></div><div className="ip-stage-line"><b>{analysis.liquidity.swept ? "Liquidity swept" : "Waiting for liquidity"}</b><span>{analysis.updatedAt ? `Updated ${new Date(analysis.updatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}` : "No verified update"}</span></div></Card>
    <div className="ip-section-head"><h2>Mechanical levels</h2><button onClick={() => go("POI")}>View ›</button></div><Card><Row label="Primary POI" note="Fib 0.71" value={price(fib?.poi)} tone="blue"/><Row label="Stop" note="Fib 0.95" value={price(fib?.stop)} tone="coral"/><Row label="Target 1" note="Fib 0.00" value={price(fib?.tp1)} tone="green"/><Row label="Target 2" note="Fib −0.21" value={price(fib?.tp2)} tone="green"/></Card></div>;
}

function Market({ go, market, analysis }: { go: (v: View) => void; market: MarketState; analysis: AnalysisState }) {
  const w = tf(analysis, "W1"), d = tf(analysis, "D1"), h4 = tf(analysis, "H4"), h1 = tf(analysis, "H1"), m15 = tf(analysis, "M15"), m5 = tf(analysis, "M5");
  const pct = market.changePct;
  return <div className="ip-page"><PageTitle eyebrow="MARKET" title="XAU/USD" sub={market.marketOpen ? "Live provider quote · refreshed every 5 seconds." : "Gold session is closed · showing the latest provider quote."}/><Card className="ip-market-card"><div className="ip-market-top"><Pill tone={market.marketOpen && market.live ? "green" : "amber"}>{market.marketOpen && market.live ? "LIVE FEED" : "MARKET CLOSED"}</Pill><span>{market.updatedAt ? new Date(market.updatedAt).toLocaleTimeString() : "No quote"}</span></div><strong>{price(market.price)}</strong><div className="ip-market-change">{pct == null ? "—" : `${pct >= 0 ? "+" : ""}${pct.toFixed(2)}%`}</div><div className="ip-wave">{Array.from({length:28},(_,i)=><i key={i} style={{height:`${20+((i*19)%65)}%`}}/>)}</div><button className="ip-primary" onClick={() => go("POI")}>Open execution radar <span>›</span></button></Card><div className="ip-section-head"><h2>Timeframe context</h2></div><Card><Row label="Weekly" value={w?.trend ?? "UNKNOWN"} tone={w?.trend === "BEARISH" ? "coral" : "green"}/><Row label="Daily" value={d?.trend ?? "UNKNOWN"} tone={d?.trend === "BEARISH" ? "coral" : "green"}/><Row label="H4" value={h4?.structure ?? "UNKNOWN"} tone="neutral"/><Row label="H1" value={h1?.structure ?? "UNKNOWN"} tone="green"/><Row label="M15" value={m15?.structure ?? "UNKNOWN"} tone="blue"/><Row label="M5" value={m5?.structure ?? "UNKNOWN"} tone="amber"/></Card></div>;
}

function POI({ analysis }: { analysis: AnalysisState }) {
  const fib = analysis.fibonacci; const state = statusLabel(analysis.status); const direction = analysis.direction ?? "UNKNOWN";
  return <div className="ip-page"><PageTitle eyebrow="EXECUTION RADAR" title="POI Monitor" sub="The system does not enter until liquidity is swept inside the POI."/><Card className="ip-poi-card"><div className="ip-poi-badge"><Pill tone={direction === "BEARISH" ? "coral" : "green"}>{direction} SETUP</Pill><span>XAU/USD · M15</span></div><strong>{price(fib?.poi)}</strong><span className="ip-poi-label">PRIMARY POI · 0.71</span><div className="ip-condition"><span className="ip-pulse"/> {analysis.liquidity.swept ? "LIQUIDITY SWEPT" : state === "UNKNOWN" ? "WAITING FOR DATA" : "WAITING FOR LIQUIDITY"}</div></Card><Card><div className="ip-card-head"><div><h3>Entry checklist</h3><p>Mechanical sequence</p></div></div>{["HTF bias","Structure shift","Valid impulse","Fib 0.71","Liquidity sweep","Entry"].map((x,i)=><div className="ip-check" key={x}><span className={i < 4 && analysis.fibonacci ? "done" : i === 4 && analysis.liquidity.swept ? "done" : i === 4 ? "next" : "locked"}>{i < 4 && analysis.fibonacci ? "✓" : i === 4 && analysis.liquidity.swept ? "✓" : i === 4 ? "•" : "—"}</span><div><b>{x}</b><small>{i < 4 && analysis.fibonacci ? "Verified" : i === 4 && analysis.liquidity.swept ? "Verified" : i === 4 ? "Required next" : "Locked"}</small></div></div>)}</Card><Card><Row label="Stop loss" value={price(fib?.stop)} tone="coral"/><Row label="Take profit 1" value={price(fib?.tp1)} tone="green"/><Row label="Take profit 2" value={price(fib?.tp2)} tone="green"/></Card></div>;
}

function Setups({ go, analysis }: { go: (v: View) => void; analysis: AnalysisState }) { return <div className="ip-page"><PageTitle eyebrow="SETUPS" title="Setup queue" sub="Only rule-compliant opportunities belong here."/><Card><div className="ip-setup-feature"><Pill tone={analysis.status === "CONFIRMED" ? "green" : "amber"}>{statusLabel(analysis.status)}</Pill><h3>XAU/USD · {analysis.direction ?? "UNKNOWN"}</h3><p>{analysis.reasons[analysis.reasons.length - 1] || "Waiting for verified analysis."}</p><button onClick={() => go("POI")}>Inspect setup <span>›</span></button></div></Card><Card><Row label="Weekly bias" value={tf(analysis,"W1")?.trend ?? "UNKNOWN"}/><Row label="Daily bias" value={tf(analysis,"D1")?.trend ?? "UNKNOWN"}/><Row label="External structure" value={tf(analysis,"H1")?.structure ?? "UNKNOWN"}/><Row label="Liquidity" value={analysis.liquidity.swept ? "SWEPT" : "WAITING"}/></Card></div>; }
function Journal() { return <div className="ip-page"><PageTitle eyebrow="JOURNAL" title="Your process" sub="Log the decision, not just the outcome."/><Card className="ip-empty"><div>＋</div><h3>No trades logged</h3><p>When a setup is executed, capture the reason, risk, and outcome here.</p><button className="ip-primary">New journal entry</button></Card><div className="ip-grid-2"><Card><small className="ip-label">DISCIPLINE</small><div className="ip-big">—</div><p>No sample yet</p></Card><Card><small className="ip-label">EXPECTANCY</small><div className="ip-big">—</div><p>Needs journal data</p></Card></div></div>; }
function Secondary({ view }: { view: View }) { const data: Record<string,[string,string,string]> = { Performance:["Performance","Measure execution quality, risk and consistency.","Analytics will use journal data."],Backtest:["Backtest","Test the exact 0.71 / 0.95 / 0 / −0.21 rules.","No results are fabricated."],Strategy:["Strategy","POI methodology","Weekly/Daily bias → structure shift → valid impulse → 0.71 POI → internal liquidity sweep → entry."],Calendar:["Calendar","Macro context","Connect an economic calendar provider to show verified events."],"AI Copilot":["AI Copilot","Verified context only","The copilot should explain deterministic analysis, never invent market conditions."],Psychology:["Psychology","Protect the process","No clear condition means no trade. Do not move the stop emotionally."],Settings:["Settings","System controls","Market data, AI provider, notifications and appearance belong here."]}; const [title,sub,body]=data[view] ?? data.Performance; return <div className="ip-page"><PageTitle eyebrow="MORE" title={title} sub={sub}/><Card className="ip-feature-copy"><Pill tone="blue">SYSTEM</Pill><h3>{title}</h3><p>{body}</p><div className="ip-note">Live market values are sourced from the configured provider. When the provider is unavailable, the interface shows an explicit unavailable state rather than a fabricated price.</div></Card></div>; }
function PageTitle({ eyebrow, title, sub }: { eyebrow: string; title: string; sub: string }) { return <div className="ip-page-title"><span>{eyebrow}</span><h1>{title}</h1><p>{sub}</p></div>; }

export default function IphoneTraderOS() {
  const [active, setActive] = useState<View>("Home"); const [moreOpen, setMoreOpen] = useState(false); const { market, analysis } = useLiveMarket();
  const go = (view: View) => { setActive(view); setMoreOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const content = active === "Home" ? <Home go={go} market={market} analysis={analysis}/> : active === "Market" ? <Market go={go} market={market} analysis={analysis}/> : active === "POI" ? <POI analysis={analysis}/> : active === "Setups" ? <Setups go={go} analysis={analysis}/> : active === "Journal" ? <Journal/> : <Secondary view={active}/>;
  return <main className="iphone-os"><header className="ip-header"><button className="ip-brand" onClick={() => go("Home")}><span>POI</span><b>Trader OS</b></button><div className="ip-symbol"><i className={market.live ? "live-dot" : ""}/> XAU/USD <small>{market.marketOpen ? "LIVE" : "CLOSED"}</small></div><button className="ip-more-top" aria-label="Open menu" onClick={() => setMoreOpen(true)}>•••</button></header><div className="ip-content">{content}</div><nav className="ip-tabbar">{primary.map(item => <button key={item.id} className={active === item.id ? "active" : ""} onClick={() => go(item.id)}><span>{item.icon}</span><b>{item.id}</b></button>)}<button className={moreOpen || !primary.some(x => x.id === active) ? "active" : ""} onClick={() => setMoreOpen(true)}><span>•••</span><b>More</b></button></nav><AnimatePresence>{moreOpen && <><motion.button className="ip-sheet-backdrop" aria-label="Close menu" onClick={() => setMoreOpen(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside className="ip-sheet" initial={{y:"100%"}} animate={{y:0}} exit={{y:"100%"}} transition={{type:"spring",stiffness:420,damping:34}}><div className="ip-sheet-grabber"/><div className="ip-sheet-head"><div><span>TRADER OS</span><h2>More</h2></div><button onClick={() => setMoreOpen(false)}>Done</button></div><div className="ip-more-list">{more.map(item => <button key={item.id} onClick={() => go(item.id)}><span className="ip-more-icon">{item.icon}</span><div><b>{item.id}</b><small>{item.desc}</small></div><em>›</em></button>)}</div></motion.aside></>}</AnimatePresence></main>;
}
